### ISSUE TITLE
Question about middleware best practices with angular 1.x

### ISSUE THREAD

**Issue by mjw56** [wbuchwalter/ng-redux#16]
Hi folks,

Thanks for this project!

I had a question around middleware, and what might be the best practices for doing such things as Promises, requests to server etc?

Is anyone creating their own middleware using this with angular 1.x (api, promise, etc...)? If so, have you run into any issues or difficulties? Are you using angular's provided utilities ($http, $q, etc.) or are you pulling in another third party lib for doing this stuff?

Any insight would be much appreciated!

Cheers
Mike

**Comment by wbuchwalter** [comment]
Hey Mike,
I'm using something similar to [this](https://github.com/wbuchwalter/tsRedux/blob/master/src/redux/promiseMiddleware.ts), in combination with `$http` for API calls (beware when browsing the code of this repo, it's all deprectated).
You can find another interesting example [here](https://github.com/e-schultz/ng-redux-nhl-stats-example/blob/master/src/middleware/http/http-middleware.js), by @e-schultz and @neilff , still using angular's utilities directly inside the middleware.

Works like a charm for me, have you encountered any problem?

**Comment by mjw56** [comment]
Thanks @wbuchwalter , this looks exactly for the type of example I was looking for. I will study this code and let you know if I find any issues in my implementation. Thanks.

**Comment by sstorie** [comment]
@wbuchwalter I'm glad I came across your note about tsRedux because it caused me to search around for available redux middleware :)

So I'm using available middleware for logging and handling promises, but I'm curious what else you consider deprecated about the tsRedux code base? If I'm learning a little from that what else would you not repeat if you worked on a typescript/redux project now?

Thanks again for publishing this code...it's been very helpful for me as I transition from many years of C#/.NET coding into modern javascript development.

**Comment by wbuchwalter** [comment]
Hey!
TsRedux is mostly correct, I said it was deprecated because it used an older version of ng-redux that is very different from the current one.
But this is mostly fixed since @cveld PR which refreshed all that.
There is probably some things that I would do slightly differently now but nothing is there is obviously bad.
Among things that you should think about before repeating them:
* Mutations: This is the big one: there is a lot of mutations in the reducers, you should not do that, I did it because I wanted to test things quickly but don't do that. Use something like `_.assign`.
* handleAction decorators: Some devs find the good old switch more explicit and less magic since TS decorators + metadata are quite obscure and not really well decorated for now
* Related to the one above, if not using decorators, you can then write your reducers as basic function, no need for a class anymore
* Actions are binded once and then injected as a service, you can do that, or you can pass the unbinded action to  `connect` in the controller where you want to use them instead. Choose the way you prefer

And last but not least, this example was mostly for my personal use, to check that redux would play nice with a use case I had, and this had to work with ~10k items, so I took some shortcut for perfomance reasons. Bottom line, if you feel like something I did is ugly and you could do it in a cleaner way, you are probably right.

**Comment by sstorie** [comment]
@wbuchwalter I really appreciate the thoughts and advice. I think I'm going to simplify my code down to use more functions while I learn and add in the typescript classes and such as I feel comfortable. The note about mutations was a good one too, as while I get that a reducer should return a copy of the state with the needed modifications, I don't think I was handling that properly. I was just updating the state object provided to the reducer, and returning it.

Next on my list is to understand how ui-router fits in (via the redux library for it of course), but this is all starting to click so hopefully that's not too bad :)
