### ISSUE TITLE
ng-model and angular binding concept discution

### ISSUE THREAD

**Issue by gilamran** [wbuchwalter/ng-redux#33]
Hi,
I've been reading about Redux, and it sounds very interesting! 
The issue that I want to raise is the conflict in the way we "suppose" to work in angular, like binding, ng-model, etc. and this new way (Redux/Flux).
Using Redux means that we are not suppose to work with ng-model or binding anymore... and only raise an action that will cause a recreation of the model.
Also, when the new state is re-created all the references are changed, and a full redraw will happen in Angular...

What do you guys think about that? I'd love to use all the abilities that we have in Angular (Modules, Injection, Templates, bla bla), with this new way of thinking, and all that comes with it.

Thanks.

**Comment by e-schultz** [comment]
You can still use ng-model, you just want to ensure that your ng-model is not bound by reference to your global application state. 

The mapStateToTarget will use _.assign to copy properties over onto your target, so that updates to your ng-model shouldn't be reflected in your global state right away. However, if you have deep object states/etc - you can still end up accidently mutating things.

Using things like Immutable JS can help prevent this, but just a bit of practice by convention to ensure you are getting a copy of the state, not a reference to it can help avoid this.

You would generally want some way to trigger an action to fire off an event to update the state, such as a button click, form submission, etc. 

If you want sort of 'real-time' syncing of the state - ie: so that each keypress is updated in the global state, you should use ng-change to fire off the actions, but you might want to make use of the ng-model-options to limit how often these are fired off (ie: on blur, or debounce, etc).

This can result in your component having a bit of local 'internal' state - how often you want to / need to sync this up with the global state depends on your use cases and needs. In my experience of working with angular for many years - it's been pretty rare that I've wanted a 'key stroke by key stroke' type of things being in sync, and usually some other use action like clicking a button to cause the rest of the application to update and say "Yup, I care about this now".

**Comment by wbuchwalter** [comment]
@gilamran Did Evan answered your questions?
I'm going to assume everything is fine if we don't hear from you.
Thanks!

**Comment by rajatvijay** [comment]
Got the point that it is a shallow copy, not a direct reference.

But what if my state is a nested object, then ng-model can mutate it.

What could be a solution here? Something like this
 
`
maptStateToThis() {
    item: angular.copy(state.item)
}
`

where item has the following strcuture in the state: 
`
item: { data: {name: "stuff", price: 250}, timestamp: 21345676543 }
`

**This way we can avoid the mutation**
