### ISSUE TITLE
ReferenceError: angular is not defined 

### ISSUE THREAD

**Issue by fritx** [wbuchwalter/ng-redux#42]
```plain
ReferenceError: angular is not defined
    at Object.<anonymous> (...\node_modules\ng-redux\lib\index.js:11:22)
```

```js
import ngReduxProvider from './components/ngRedux';

export default angular.module('ngRedux', [])
  .provider('$ngRedux', ngReduxProvider)
  .name;
```

When I use it in iojs 1.2.0, it seems that angular is not available in lib/index.js 11:22

**Comment by wbuchwalter** [comment]
ng-redux is a lib to wire angularjs with Redux, maybe there is something I misunderstood, but how are you planning on using angularjs server side?
Seems like there is some confusion.

**Comment by fritx** [comment]
Oh I get it. Sorry for unclear description.
I was using ng-redux in NW.js (node-webkit). It is backend-side mixed with frontend-side.
And I prefer to use `require()` but it seems to break.
I'm now using `<script>` way and it is fine.

**Comment by wbuchwalter** [comment]
I don't think you can require angularjs. 
A lot of libraries that are used both backend and frontend will do something like that:
```javascript
 if (hasModule) {
        module.exports = myLib;
  }  else {
        window.myLib = myLib
 }
```
But angular always define itself on the window no matter what since it assume nobody will use it in a node environment:
```Javascript
angular  = window.angular || (window.angular = {}),
```
So since angular never exports anything, requiring it will just returns `undefined`, hence your problem.

You probably don't have any other choice than using `<script>`.

**Comment by fritx** [comment]
Cool, thanks.

**Comment by simplesmiler** [comment]
@fritx by the way, you can use commonjs-style `require('angular')` with browserify and browserify-shim, but it requires you to integrate these tools into your workflow.

**Comment by fritx** [comment]
It's awesome. Never used it ;P
