### ISSUE TITLE
Using ng-redux without ES6 modules

### ISSUE THREAD

**Issue by nmehta6** [wbuchwalter/ng-redux#59]
I am consuming ng-redux in a project that does not use any modules. The challenge that I ran into with this approach is with the `config` block. If you have any suggestions for this, I would greatly appreciate it!

```
angular.module('counter', [ngRedux])
  .config(($ngReduxProvider) => {
    $ngReduxProvider.createStoreWith(rootReducer, [thunk], [DevTools.instrument()]);
  });
```

What would be the best way to create reducers here? Should they be $providers so they can be injected in the config block?

If ngRedux provided a factory instead of a provider it could be setup in a `run` block and everything (reducers, actionCreators, etc.) can be defined as `factory`.

I understand that using ES6 modules is great and brings lots of benefits. I don't have that setup for my angular project though.

**Comment by jbalboni** [comment]
Are you using any bundler? In the app I work on, reducers are plain JS and are included using require('/path/to/some/reducer.js'). No ES6 modules, but we are using Browserify/CommonJS.

**Comment by nmehta6** [comment]
No, I don't have any bundlers at the moment. I am relying solely on the minimal load order that angular provides (with config blocks and providers, runs and factories). I haven't had any need for a bundler since I am completely inside the angular world.

**Comment by wbuchwalter** [comment]
Much like what @jbalboni said.
Using a bundler is the best solution here in my opinion.

Most of redux related things make the assumption that you are using one. 
For example middlewares like `redux-thunk`, `redux-devtools` and many other things are exposed as module. 

If you have a very specific reason for not having a bundler, you could still pass a dummy function to `createStoreWith` and then use `replaceReducer` after the config phase to use the reducers you defined as factory, that should work (never tried, so maybe I'm forgetting something), but you ought to really not want a bundler before going down that road.

I won't be adding support for reducers as service (like what was done for middlewares) because in my opinion it facilitate two very bad things:
* using dependency injection in your reducer (you should keep them pure).
* accessing your reducers from anywhere, which you should never have to do.

**Comment by nmehta6** [comment]
Thank you for this nice explanation. It makes sense to just use a bundler like you suggested.

**Comment by mnn** [comment]
> using dependency injection in your reducer (you should keep them pure).

I don't think using injection implies impure reducer (certainly not always). I wanted to inject a service with pure methods to be used by a reducer - using pure function from pure function would result in a pure function.
