### ISSUE TITLE
using ng-redux without injecting $scope

### ISSUE THREAD

**Issue by orizens** [wbuchwalter/ng-redux#60]
A best practice for controllers angular 1.x includes few concepts: 
1. using controllerAs 
2. avoid using $scope 
3. keep logics in services 

Is there a way to use ngRedux without injecting "$scope"? 
Is there a way to use ngRedux in services? 

Thanks.

**Comment by wbuchwalter** [comment]
Using `$scope` in itself is not a bad practice, it's what people do with it that often end up being one.

In the case of ng-redux, `$scope` is used solely to hook on the `$destroy` event to unsubscribe from the store. 
If you don't want to inject `$scope`, you could manually unsubscribe in your transient component when it is disposed (for example, when the user click on a close button or something like that), that will work just as fine.

You can totally use ng-redux in a service, and since services are never disposed, you don't need to unsubscribe.

**Comment by orizens** [comment]
Thanks.
So, if i use it in a service, all in all, will ng-redux, upon change, run the entire digest loop from root?

**Comment by wbuchwalter** [comment]
Where you use `ng-redux` has no impact on the digest cycle (`ng-redux` does not trigger a digest cycle itself), so it won't change anything, it will be angular that will decide wether what you did may have affected the state of the DOM.

To be exact, the only place where `ng-redux` may have an effect on the digest loop is in the middleware: All your middlewares are wrapped in a `$evalAsync`, so that any timeout in one of your custom middleware does not get you out of the angular world, but this has no impact on what we are discussing here.

(I'm closing this issue, since it is not really one, but feel free to continue the discussion)

**Comment by orizens** [comment]
Great.
Thanks.
I'm looking into adding ng-redux to the style guide 
https://github.com/orizens/angular-es2015-styleguide

**Comment by danpantry** [comment]
I've actually created a boilerplate wrapper about ngRedux to avoid `$scope` for this exact reason. It's really simple:

```
interface ComponentController {
  $inject?: string[];
  mapState: (state: any) => any;
  new (...args: any[]);
}

function connectToStores(controller: ComponentController) {
  return function ConnectedComponent($scope, $ngRedux, $injector) {
    const unsubscribe = $ngRedux.connect(controller.mapState);
    $injector.invoke(controller, this, { $scope });
    $scope.$on('$destroy', unsubscribe);
  };
}
```

You can just decorate your controller with this structure.

```
class MyController {
  static mapState(state: any) {
    return {
      foo: state.foo
    };
  }
}
export default connectToStores(MyController);
```

This is created in the context of using angular 1.X components, though (requires at least angular 1.3+ with [a shim](https://www.npmjs.com/package/angular-component) or 1.5+ otherwise. If you can't guarantee that `connectToStores` will receive a `$scope` (for whatever reason), just inject `$rootScope` and create a new scope instead; you can do this using `$injector`, but I haven't written the code for that as it is not a use-case I want to support.

**Comment by danpantry** [comment]
Here's a boilerplate wrapper I came up with to avoid using `$scope` in the controller:

```
function connectToStores(controller) {
  return function ($scope, $ngRedux, $controller) {
    const instance = $controller(controller, { $scope });
    const unsubscribe = $ngRedux.connect(instance.mapState)(this);
    $scope.$on('$destroy', unsubscribe);
    // TODO: you may wish to extend "this" with the original instance, instead of
    // applying the slice to this instead.
    // angular.extend(this, instance);
  };
}
```

it's only intended to be used in a `controllerAs` scenario (directives with `controllerAs`, route handlers in uiRouter with `controllerAs` or components in Angular 1.5+); it might fall down when you don't use `controllerAs`.

I have no issue with using `$scope` in a controller per sé, but there's a little bit of boilerplate involved in connecting to a component with ngRedux. Example of use:

```
class UserGreetingCtrl {
  mapState(state: any) {
    return {
      username: state.username
    };
  }

  // @ngInject
  constructor($scope) {}
}

export default {
  controller: connectToStores(UserGreetingCtrl),
  controllerAs: 'greeting',
  template: '<h1>Hello, {{greeting.username}}</h1>'
};
```

Note that I've put an `@ngInject` annotation and in the constructor required `$scope`. Because we're creating a controller with `$controller` for a component we just want to pass in the `$scope` created for that component which is passed to us in the original controller constructor. `$controller` will resolve dependencies, so you'll still want an `$inject` on your controller constructor (in my case I used `// @ngInject` because I have `ng-annotate` in a build step.

The call to `$ngRedux.connect()` feels hacky, but it works.

**Comment by zourtney** [comment]
Angular 1.5+ components can avoid `$scope` usage by putting cleanup in the `$onDestroy` hook. Not as concise, but may improve readability.

```javascript
class MyComponentCtrl {
  unsubscribe;

  /* @ngInject */
  constructor($ngRedux) {
    this.unsubscribe = $ngRedux.connect(...)(this);
  }

  $onDestroy() {
    this.unsubscribe();
  }
}
```

PS: sorry for posting on a closed issue...it just seemed worth mentioning. It might even be worth adding to the docs.

**Comment by danpantry** [comment]
@zourtney  you could use `$onInit()` instead of the constructor here; although it does mean storing a reference to `$ngRedux`, it ensures that the connection is only made when the component is ready.
