### ISSUE TITLE
argument seems to miss in reselect

### ISSUE THREAD

**Issue by iamdey** [wbuchwalter/ng-redux#66]
Here, https://github.com/wbuchwalter/ng-redux/blob/master/src/components/connector.js#L68

```
function getStateSlice(state, mapStateToScope) {
  const slice = mapStateToScope(state);
```

A `props` argument should be passed (I am newbie in redux/reselect, so I can't tell how, sorry).
I tried to follow [the documentation of reselect](https://github.com/rackt/reselect#accessing-react-props-in-selectors).

Here is my use case : 

```
import {createSelector} from 'reselect';

const applicationSelector = createSelector(
  (state, ownProps) => {
    console.log('applicationSelector 1', state, ownProps); //got state and undefined, I would have {foo: 'bar'}
    return state.router;
  },
  routerState => routerState.name
});

export class LayoutApplicationSwitcherController {
  constructor($scope, $ngRedux) {
    'ngInject';
    this.foo = 'bar';
    $scope.$on('$destroy', $ngRedux.connect(applicationSelector)(this));
  }
}
```

**Comment by iamdey** [comment]
oups, I just found connect is not part of redux but redux-react, and the API [is not the same](https://github.com/reactjs/react-redux/blob/master/docs/api.md#connectmapstatetoprops-mapdispatchtoprops-mergeprops-options) (but it would be pretty cool to be similar ;) )

**Comment by wbuchwalter** [comment]
Yea, this is something specific to react.
We don't really have an equivalent to the `props` object in AngularJS.
Passing a reference to the controller could work with the `controllerAs` syntax, but will not work otherwise  etc.
I'm closing this issue since I don't plan on doing this in a foreseeable future, and this is not really an issue per se, but if someone wants to play with that and submit a PR it's welcome.
Thanks!

**Comment by iamdey** [comment]
Thank you for the answer. Well if I have no better choices, I may try something.

Btw, thanks for developing this library.
